- Mobile.BuildTools/Generators/SecretsClassGenerator.cs
- ReadMe.md
The existing behavior for the Secrets task has added the need to exclude two files from source control.  This is good in the sense that it lessens the feeling of "Magic" since the generated code file is fully visible inside the project. This however also makes it more likely that values could be exposed to source control. 
The secrets class will now prefer to be generated in the Intermediate Output Folder (obj folder). This reduces the likelihood of the generated class being included in source control, and minimizes the change to the ignore file to only ignore secrets.json. 
If the Secrets.cs exists in the project path it will continue to update the in-project file. This provides backwards compatibility and ensures that it is easy for developers to not feel like there is "too much magic".
> Remove in project secrets class

- Mobile.BuildTools/Generators/SecretsClassGenerator.cs
Newtonsoft capitalizes booleans in the JToken. This results in a build error when injecting boolean values with the Secrets generator.
Booleans outputs now call ToLower to ensure proper code generation
> fix capitalized boolean output

- Mobile.BuildTools/build/Mobile.BuildTools.props
- Mobile.BuildTools/build/Mobile.BuildTools.targets
- ReadMe.md
Adds enhancement from issue #11. Generated APK, IPA, and dSYM are now copied to the Artifacts directory under the `$(SolutionDir)`, and in `$(Build.ArtifactStagingDirectory)` on VSTS.
- IsAppCenter
- IsAppVeyor
- IsJenkins
- IsVSTS
- IsBuildHost
- BuildToolsArtifactOutputPath - this can be used to override the default path locally but not on VSTS
- DisableBuildToolsArtifactCopy - setting this to true will disable this copy tasks
> Outputs copy

- Mobile.BuildTools.Tests/Fixtures/SecretsClassGeneratorFixture.cs
- Mobile.BuildTools/Generators/SecretsClassGenerator.cs
Fixes #30 
Ensures that when the Project Folder Name is different from the Root Namespace that the Root Namespace will be used. Logs warning if the Root Namespace is null/empty.
> Fix custom Namespaces

- Mobile.BuildTools.Tests/Templates/Css/style.min.css
- Mobile.BuildTools.Tests/Templates/Css/style2.min.css
- Mobile.BuildTools/Tasks/ScssProcessorTask.cs
Looks like Xamarin is expecting all CSS declarations to end with a semicolon. Was having trouble with the last value from a .scss not being applied after Uglify created the CSS. 
Added TermSemicolons option to CssSettings.
> Add terminating semicolon during minify

- Directory.build.props
This was causing the pack to fail.
> The package path must be an actual relative file name

- docs/schemas/v2/buildtools.schema.json
- samples/BuildToolsSample/buildtools.json
- samples/BuildToolsSample/src/platform/BuildToolsSample.Android/Properties/AndroidManifest.xml
- samples/BuildToolsSample/src/platform/BuildToolsSample.iOS/Info.plist
- src/Mobile.BuildTools/AndroidManifest.targets
- src/Mobile.BuildTools/Constants.cs
- src/Mobile.BuildTools/Generators/Manifests/BaseTemplatedManifestGenerator.cs
- src/Mobile.BuildTools/Generators/Manifests/DefaultTemplatedManifestGenerator.cs
- src/Mobile.BuildTools/Generators/Manifests/TemplatedAndroidAppManifestGenerator.cs
- src/Mobile.BuildTools/Generators/Manifests/TemplatedPlistGenerator.cs
- src/Mobile.BuildTools/Generators/Secrets/BuildHostSecretsGenerator.cs
- src/Mobile.BuildTools/Generators/Secrets/SecretsClassGenerator.cs
- src/Mobile.BuildTools/Generators/Versioning/AndroidAutomaticBuildVersionGenerator.cs
- src/Mobile.BuildTools/Generators/Versioning/BuildVersionGeneratorBase.cs
- src/Mobile.BuildTools/Generators/Versioning/iOSAutomaticBuildVersionGenerator.cs
- src/Mobile.BuildTools/Models/BuildToolsConfig.cs
- src/Mobile.BuildTools/Models/EnvironmentSettings.cs
- src/Mobile.BuildTools/ReadMe.txt
- src/Mobile.BuildTools/Tasks/AutomaticBuildVersioningTask.cs
- src/Mobile.BuildTools/Tasks/BuildEnvironmentDumpTask.cs
- src/Mobile.BuildTools/Tasks/TemplateManifestTask.cs
- src/Mobile.BuildTools/Utils/EnvironmentAnalyzer.cs
- tests/Mobile.BuildTools.Tests/Fixtures/Generators/AndroidAutomaticBuildVersionGeneratorFixture.cs
- tests/Mobile.BuildTools.Tests/Fixtures/Generators/AppManifestGeneratorFixture.cs
Adds the ability to add non-sensitive default values to the buildtools.json that are used by the Secrets class generator and the template manifest task. This allows both generically default variables and build configuration based variables.
The defaults can now be added in the buildtools.json as follows:
```json
{
"environment": {
"defaults": {
"AppId": "com.avantipoint.awesomeapp"
},
"configuration": {
"Debug": {
"AppId": "com.avantipoint.awesomeappdev"
}
}
}
}
```
Given this sample I might tokenize the package name in the AndroidManifest or the CFBundleIdentifier in the Info.plist, this would then allow me to automatically set the name to `com.avantipoint.awesomeappdev` while debugging the app, and `com.avantipoint.awesomeapp` on all other builds. As a result I can easily ensure that I …
> [Enhancement] Add Default Environment variables to buildtools.json

- src/Mobile.BuildTools/AndroidManifest.targets
The execution point for the HandleAndroidManifest was running too late. As a result when the package name is tokenized like `$AppId$` and we replace it with `com.company.appname`, the MonoAndroid SDK has already set properties where it has sanitized `$AppId$` as `x_AppId.x_AppId`. This updates the point that we run to prevent this from occurring.
> fix manifest execution point

- src/Mobile.BuildTools/Generators/Secrets/SecretsClassGenerator.cs
- src/Mobile.BuildTools/Models/Secrets/Accessibility.cs
- src/Mobile.BuildTools/Models/Secrets/SecretsConfig.cs
- tests/Mobile.BuildTools.Tests/Fixtures/Generators/SecretsClassGeneratorFixture.cs
PR for #172.
Adds the ability to configure the generated Secrets class and property accessibility level to one of the following values:
- `Internal` - default value
- `Public`
> #172 Configure generated Secrets class accessibility

- docs/schemas/v2/buildtools.schema.json
- src/Mobile.BuildTools/Models/Secrets/SecretsConfig.cs
- src/Mobile.BuildTools/Tasks/SecretsJsonTask.cs
Adds support for setting a Root namespace to use for the Secrets class generation. This will override the default Root namespace of the project. This can be used in cases where you need to access the Secrets class from a shared project used across multiple platform heads which would each have a different Root Namespace.
- fixes #210
> add support for Root Namespace

- src/Mobile.BuildTools/Mobile.BuildTools.csproj
- src/Mobile.BuildTools/buildTransitive/Mobile.BuildTools.props
- src/Mobile.BuildTools/buildTransitive/Mobile.BuildTools.targets
Adds build props / targets to buildTransitive directory of the package. This will allow other packages to reference Mobile.BuildTools and have the build targets still automatically imported.
- closes #122
> add support for transitive build

- src/Mobile.BuildTools/Models/EnvironmentSettings.cs
- src/Mobile.BuildTools/Models/ImageResize.cs
- src/Mobile.BuildTools/Models/Secrets/SecretsConfig.cs
When reading the buildtools.json the helper does activate any null values, however this does not address any collections which we may expect to iterate on. This ensures that when creating a new instance of our config sections they initialize any collections that they contain so we avoid any unnecessary null reference exceptions
> prevent null references

- Packages.props
- src/Mobile.BuildTools/Utils/ImageSearchUtil.cs
- tests/Mobile.BuildTools.Tests/Fixtures/Tasks/CollectImageAssetsTaskFixture.cs
- tests/Mobile.BuildTools.Tests/Fixtures/Utils/ImageSearchUtilityFixture.cs
- tests/Mobile.BuildTools.Tests/Mobile.BuildTools.Tests.csproj
Currently if you provide a path for Images to process, but the path does not exist this will result in an unhandled DirectoryNotFoundException. This resolves the issue by validating that the path exists and logging a warning when a directory cannot be found at a given path.
> Log warning and remove paths that do not exist from search directories

- Packages.props
- src/Mobile.BuildTools/Mobile.BuildTools.csproj
This resolves a build lock up or 'unknown build failure' when building iOS/Android and using SVG images
> Migrated Svg.Picture to it's replacement Svg.Model

- Packages.props
- src/Mobile.BuildTools.Configuration/Mobile.BuildTools.Configuration.csproj
- src/Mobile.BuildTools.Configuration/build/Mobile.BuildTools.Configuration.props
- src/Mobile.BuildTools.Reference/Mobile.BuildTools.Reference.csproj
- src/Mobile.BuildTools/Mobile.BuildTools.props
There is currently a pretty loose connection between Mobile.BuildTools and Mobile.BuildTools.Configuration. This kept all of the build props/targets as part of the Mobile.BuildTools... it also results in a pretty annoying inclusion of the app.config on the iOS/Android project even when the file does not exist. This updates the props so that it is now part of the Configuration project, and you will only get the Include when you actually have the Configuration package referenced.
There isn't really anything I can do for the file showing up. The legacy project sdk's for Android/iOS aren't as capable of dynamic includes like the newer MSBuild Sdks
> Move app.config props

- src/Mobile.BuildTools/MonoAndroid.targets
Adds Support for copying generated AAB or APK for Android Projects to the Artifacts folder.
- Fixes #211
> Support AAB copy

- src/Mobile.BuildTools.Reference/Utils/ConfigHelper.shared.cs
- tests/Mobile.BuildTools.Tests/Fixtures/Utils/BuildToolsConfigFixture.cs
This resolves #259 
Reworked unit tests to rely on the logic that creates the default file within the framework rather than creating it upfront.
> Safely handle no build tools.json config file

- src/Mobile.BuildTools/Tasks/LocateBuildToolsConfigTask.cs
Disables the `buildtools.json` config file validation to workaround #263
> Disabled config validation

- src/Mobile.BuildTools.Reference/Utils/EnvironmentAnalyzer.cs
- tests/Mobile.BuildTools.Tests/Fixtures/FixtureBase.cs
- tests/Mobile.BuildTools.Tests/Fixtures/Generators/AppleImageCollectionGeneratorFixture.cs
- tests/Mobile.BuildTools.Tests/Fixtures/Generators/ImageCollectionGeneratorFixture.cs
- tests/Mobile.BuildTools.Tests/Fixtures/Utils/EnvironmentAnalyzerFixture.cs
This update allows the lookup for the appsettings.json or deprecated secrets.json to occur starting with the Project Directory and recursively steps up to the Solution Directory. This enables developers who may want to provide a appsettings.json to be shared between multiple projects, without it being in the solution root.
Updates the tests to have unique project/solution directory for testing.
> recursive lookup from Project Directory to the Solution Directory

- src/Mobile.BuildTools.Reference/Generators/Images/AppleImageCollectionGenerator.cs
- src/Mobile.BuildTools.Reference/Generators/Images/ImageCollectionGeneratorBase.cs
- src/Mobile.BuildTools.Reference/Utils/ConfigHelper.cs
- src/Mobile.BuildTools.Reference/Utils/ConfigHelper.shared.cs
- src/Mobile.BuildTools/Drawing/ImageBase.cs
- tests/Mobile.BuildTools.Tests/Fixtures/Drawing/ImageBaseFixture.cs
- tests/Mobile.BuildTools.Tests/Fixtures/Generators/ImageCollectionGeneratorFixture.cs
Watermark `sourceFile` paths are now correctly converted to a full file path during image asset collection ready for the image resizer to process appropriately.
> Resolve issue 285 watermark image

- docs/continuous-integration/setup.md
As mentioned in this issue #272 the default in the code is BuildTools_ and not Secret_ as in Mobile Builds tools version 1.x
> The default seems to be BuildTools_ instead of Secret_

- docs/config/app.config/in-code.md
- docs/config/app.config/transformations.md
- samples/AppConfigSample/src/AppConfigSample.Android/AppConfigSample.Android.csproj
- samples/AppConfigSample/src/AppConfigSample.Android/Assets/app.debug.config
- samples/AppConfigSample/src/AppConfigSample.Android/Assets/app.foo.config
- samples/AppConfigSample/src/AppConfigSample.Android/Assets/app.release.config
- samples/AppConfigSample/src/AppConfigSample.Android/SplashActivity.cs
- samples/AppConfigSample/src/AppConfigSample.iOS/Resources/app.debug.config
- samples/AppConfigSample/src/AppConfigSample.iOS/Resources/app.foo.config
- samples/AppConfigSample/src/AppConfigSample.iOS/Resources/app.release.config
This PR addresses issue #316
- Updated the sample project for app.config to use the `xdt:Locator` attribute where any Replace transforms are performed. This will help prevent developers encountering some of the funky behaviour the `Microsoft.Web.XmlTransform` library performs when this attribute is omitted from the transformation xml.
- Bumped sample app android version target & fixed a dead namespace (it wasn't building locally so I thought I'd bundle those changes)
- Updated the docs to reflect these changes, with links to the Microsoft docs where relevant.
- Updated the `ConfigurationManager` init code to mention & explain the `enableRuntimeEnvironments` flag
> Updated docs & samples for app.config

- .gitignore
- Directory.Build.props
- Directory.Build.targets
- Directory.Packages.props
- src/Mobile.BuildTools.Configuration/Mobile.BuildTools.Configuration.csproj
Add this targets file alongside `Directory.Build.targets` named `Directory.Build.targets.user` (which will now be ignored in commits):
```xml
<Project>
<PropertyGroup>
<RestoreSources>https://pkg.kzu.io/index.json;https://api.nuget.org/v3/index.json</RestoreSources>
</PropertyGroup>
<ItemGroup>
<PackageVersion Update="NuGetizer" Version="42.42.42-main.807" />
</ItemGroup>
</Project>
```
This adds the CI nugetizer package feed and the latest build from main, which contains the fix for platform-suffixed target frameworks: https://github.com/devlooped/nugetizer/pull/306
> Minor tweaks to improve nugetizability

- Directory.Packages.props
- src/Mobile.BuildTools.Configuration/AppConfigElement.cs
- src/Mobile.BuildTools.Configuration/AppConfigProvider.cs
- src/Mobile.BuildTools.Configuration/AppConfigSource.cs
- src/Mobile.BuildTools.Configuration/BuildToolsConfigurationExtensions.cs
- src/Mobile.BuildTools.Configuration/ChangeCallbackRegistrar.cs
- src/Mobile.BuildTools.Configuration/ConfigurationKeyComparer.cs
- src/Mobile.BuildTools.Configuration/ConfigurationManagerImplementation.cs
- src/Mobile.BuildTools.Configuration/ConfigurationReloadToken.cs
- src/Mobile.BuildTools.Configuration/EmptyDisposable.cs
- src/Mobile.BuildTools.Configuration/IConfigurationManager.cs
- src/Mobile.BuildTools.Configuration/Mobile.BuildTools.Configuration.csproj
- tests/Mobile.BuildTools.Configuration.Tests/ConfigurationManagerTests.cs
- tests/Mobile.BuildTools.Configuration.Tests/MicrosoftExtensionsFixture.cs
- tests/Mobile.BuildTools.Configuration.Tests/Mobile.BuildTools.Configuration.Tests.csproj
- tests/Mobile.BuildTools.Configuration.Tests/app.config
This adds a dependency on Microsoft.Extensions.Configuration and adds a ConfigurationSource using the Mobile.BuildTools IConfigurationManager. This means that whether relying on an updated app.config as part of your project or changing environments at runtime you can get the updated configuration settings using the mechanisms you are used to with Microsoft.Extensions.Configuration.
> Adding Microsoft.Extensions.Configuration Provider

- src/Mobile.BuildTools.AppSettings/Generators/AppSettingsGenerator.cs
- src/Mobile.BuildTools.AppSettings/Generators/GeneratorBase.cs
- src/Mobile.BuildTools.Core/Mobile.BuildTools.Core.targets
- src/Mobile.BuildTools.Core/Tasks/EnvironmentSettingsTask.cs
- src/Mobile.BuildTools.Reference/Utils/BuildEnvironment.cs
- tests/Mobile.BuildTools.AppSettings.Tests/Sources/AddsSimpleProperty/buildtools.env
- tests/Mobile.BuildTools.AppSettings.Tests/Sources/UsesSettingsOverDefault/buildtools.env
Adding ProjectName and RootNamespace to BuildConfiguration file
> Adding MSBuild Props to BuildEnvironment file

- src/Mobile.BuildTools.AppManifests/ReadMe.md
- src/Mobile.BuildTools.AppSettings/ReadMe.md
- src/Mobile.BuildTools.Configuration/ReadMe.md
- src/Mobile.BuildTools.Images/ReadMe.md
> Updating ReadMe's
