Mobile.BuildTools.Tests/Fixtures/ScssProcessorTaskFixture.cs
Mobile.BuildTools.Tests/Mobile.BuildTools.Tests.csproj
Mobile.BuildTools.Tests/Templates/Css/style.css
Mobile.BuildTools.Tests/Templates/Sass/_colors.sass
Mobile.BuildTools.Tests/Templates/Sass/_fonts.sass
Mobile.BuildTools.Tests/Templates/Sass/style.sass
Mobile.BuildTools.Tests/Templates/Scss/_colors.scss
Mobile.BuildTools.Tests/Templates/Scss/_fonts.scss
Mobile.BuildTools.Tests/Templates/Scss/style.scss
Mobile.BuildTools.Tests/Templates/Scss/style2.scss
Mobile.BuildTools/Mobile.BuildTools.csproj
Mobile.BuildTools/Tasks/ScssProcessorTask.cs
Mobile.BuildTools/build/Mobile.BuildTools.targets

This supports Sass 3 (Scss). Compiled Sass is minified and added to the build pipeline but not the project. Adds support as outlined in #16

Support for Scss Processing

---

Mobile.BuildTools/Utils/CIBuildEnvironmentUtils.cs
Mobile.BuildTools/build/Mobile.BuildTools.props
ReadMe.md

Adds explicit support for Team City #29

Support for TeamCity

---

src/Mobile.BuildTools/Tasks/TemplateManifestTask.cs

This is related to #87 
The generator is now properly instantiated and will run.

Fixed android generator assignment

---

src/Mobile.BuildTools/Configuration/MetaData.cs
src/Mobile.BuildTools/ConfigurationManager.targets
src/Mobile.BuildTools/Constants.cs
src/Mobile.BuildTools/Generators/AppConfig/ConfigurationManagerTransformationGenerator.cs
src/Mobile.BuildTools/Generators/Images/ImageCollectionGeneratorBase.cs
src/Mobile.BuildTools/Models/Configuration/ExpectedAppConfig.cs
src/Mobile.BuildTools/MonoAndroid.targets
src/Mobile.BuildTools/Tasks/AppConfigCopyTask.cs
src/Mobile.BuildTools/Tasks/ConfigurationManagerHandlerTask.cs
src/Mobile.BuildTools/iOS.targets
tests/Mobile.BuildTools.Tests/Fixtures/ImageCollectionGeneratorFixture.cs

Resolves issue with app.config not being transformed on build.

Transform App.config on Build

---

src/Mobile.BuildTools/Generators/ReleaseNotesGenerator.cs

Directory check for marker file path.

added directory check for release notes marker file - fixes #121

---

src/Mobile.BuildTools/Generators/Images/ImageCollectionGeneratorBase.cs

I have not tested further than the fact this compiles yet but I plan to shortly

Officially support .svg extension

---

samples/BuildToolsSample/images/android/icon.json
src/Mobile.BuildTools.Reference/Generators/Images/AndroidImageCollectionGenerator.cs
src/Mobile.BuildTools/Tasks/CollectImageAssetsTask.cs

Fixes the padding on Android Icons

Fix Android Image Padding

---

src/Mobile.BuildTools.Configuration/Platform/Apple/ConfigurationManager.apple.cs
src/Mobile.BuildTools.Configuration/Platform/Droid/ConfigurationManager.android.cs
src/Mobile.BuildTools.XamarinSdk/Mobile.BuildTools.XamarinSdk.csproj
tests/Mobile.BuildTools.Tests/Fixtures/Generators/AppManifestGeneratorFixture.cs

Fixes the missing XamarinSDK dll in the nuget package.

Fix missing dll

---

docs/schemas/v2/buildtools.schema.json
src/Mobile.BuildTools/ReadMe.txt

Updates the Mobile.BuildTools ReadMe & schema for Environment Settings

update package readme

---

samples/BuildToolsSample/src/platform/BuildToolsSample.iOS/Info.plist
src/Mobile.BuildTools/AndroidManifest.targets
src/Mobile.BuildTools/AppleManifests.targets
src/Mobile.BuildTools/Generators/Manifests/TemplatedAndroidAppManifestGenerator.cs
src/Mobile.BuildTools/Generators/Versioning/AndroidAutomaticBuildVersionGenerator.cs
src/Mobile.BuildTools/Generators/Versioning/BuildVersionGeneratorBase.cs
src/Mobile.BuildTools/Tasks/AutomaticBuildVersioningTask.cs
src/Mobile.BuildTools/Tasks/TemplateManifestTask.cs

Adds support for processing Templated Info.plist and app verisoning
Fixes issue with AndroidManifest on Mac
- closes #254
- closes #185

Support processing Info.plist

---

src/Mobile.BuildTools.Reference/Utils/CIBuildEnvironmentUtils.cs
src/Mobile.BuildTools/Mobile.BuildTools.props

Adding support for determining when running in GitHub Actions or BitBucket Pipelines.
- closes #137

Add support for GitHub Actions and BitBucket Pipelines

---

src/Mobile.BuildTools.Reference/Generators/Images/UwpImageCollectionGenerator.cs

Adding 125 & 150 scale for UWP

add 125 & 150 scale for UWP

---

docs/appendix/json-schemas.md
docs/appendix/msbuild-props.md
docs/appendix/upgrade.md
docs/faq.md
docs/index.md

doc updates

---

src/Mobile.BuildTools.Reference/Utils/CIBuildEnvironmentUtils.cs
src/Mobile.BuildTools/Mobile.BuildTools.props

Updates the Environment Check to understand Travis CI default variables and return the Travis CI Build Number when building using Travis CI.

add support for TravisCI

---

.github/workflows/ci.yml
.github/workflows/pr.yml
.github/workflows/start-release.yml
Directory.Packages.props
src/Mobile.BuildTools.Configuration/Mobile.BuildTools.Configuration.csproj
src/Mobile.BuildTools.Reference/Utils/StringExtensions.cs
src/Mobile.BuildTools.XamarinSdk/Mobile.BuildTools.XamarinSdk.csproj
tests/Mobile.BuildTools.Configuration.Tests/Mobile.BuildTools.Configuration.Tests.csproj
tests/Mobile.BuildTools.Tests/Mobile.BuildTools.Tests.csproj

Update for net8

---

docs/config/appsettings/index.md

Update truncated docs.

---

.github/workflows/gh-pages.yml

Update docs build

---

.github/workflows/gh-pages.yml

Update deploy key

---

.github/workflows/ci.yml
.github/workflows/pr.yml
Directory.Build.targets
ReadMe.md
docs/schemas/v2/resourceDefinition.schema.json
src/Mobile.BuildTools.AppManifests/AndroidManifest.targets
src/Mobile.BuildTools.AppManifests/AppleManifests.targets
src/Mobile.BuildTools.AppManifests/GitVersioning.targets
src/Mobile.BuildTools.AppSettings/Mobile.BuildTools.AppSettings.csproj
src/Mobile.BuildTools.Configuration.MSBuild/Tasks/AppConfigCopyTask.cs
src/Mobile.BuildTools.Configuration/build/Mobile.BuildTools.Configuration.targets
src/Mobile.BuildTools.Core/Mobile.BuildTools.Core.targets
src/Mobile.BuildTools.Core/Tasks/EnvironmentSettingsTask.cs
src/Mobile.BuildTools.Images/Mobile.BuildTools.Images.targets
src/Mobile.BuildTools.Images/Tasks/CollectImageAssetsTask.cs
src/Mobile.BuildTools.Reference/Generators/Images/AndroidImageCollectionGenerator.cs
src/Mobile.BuildTools.Reference/Generators/Images/AppleImageCollectionGenerator.cs
src/Mobile.BuildTools.Reference/Generators/Images/UwpImageCollectionGenerator.cs
src/Mobile.BuildTools.Reference/IO/DirectoryInfoEqualityComparer.cs
src/Mobile.BuildTools.Reference/Models/AppIcons/ResourceDefinition.cs
src/Mobile.BuildTools.Reference/Utils/EnvironmentAnalyzer.cs
src/Mobile.BuildTools.Reference/Utils/Platform.cs
src/Mobile.BuildTools.Reference/Utils/StringExtensions.cs
src/Mobile.BuildTools/Mac.targets
src/Mobile.BuildTools/Mobile.BuildTools.targets
tests/Mobile.BuildTools.Tests/Fixtures/Extensions/PlatformExtensionsFixture.cs
tests/Mobile.BuildTools.Tests/Fixtures/Generators/ImageCollectionGeneratorFixture.cs
tests/Mobile.BuildTools.Tests/Fixtures/Utils/EnvironmentAnalyzerFixture.cs

Fixing TargetFramework evaluation to determine platform

Fix AppSettings Lookup

---

Directory.Build.targets
src/Mobile.BuildTools.AppSettings/ReadMe.md
src/Mobile.BuildTools.Core/ReadMe.md

Adding Package ReadMe

---

Directory.Build.props
Directory.Build.targets
Directory.Packages.props
src/Mobile.BuildTools/Mobile.BuildTools.csproj

Updates default NuGet packaging properties. Packs License and Icon

Update NuGet properties

---

Directory.Build.props

Setting ReadMe filename for NuGet.org

Set ReadMe filename

---

.github/workflows/pr.yml
E2E/E2E.Tests/E2E.Tests.csproj

Adds matrix build for e2e tests. This will validate the generated NuGet package for the AppSettings works across Windows, Linux and MacOS build agents.

e2e testing
